import type { BranchPlan, BranchPlanNode } from "./types.js";

export type BranchAllocationMode = "per-ticket" | "shared" | "mixed";

export interface BranchPresentation {
  allocationMode: BranchAllocationMode;
  description: "one branch per ticket" | "one shared branch" | "mixed shared and per-ticket branches" | "stacked delivery branches";
  banner: string;
  prompt: string;
}

export interface BranchPresentationOptions {
  stacked?: boolean;
  resumed?: boolean;
}

export function branchPlanLogMetadata(plan: BranchPlan, presentation: BranchPresentation): Record<string, unknown> {
  return {
    baseRef: plan.baseRef,
    tickets: plan.nodes.map((node) => node.ticket.id),
    branches: plan.nodes.map((node) => ({ ticket: node.ticket.id, branch: node.branch, base: node.baseBranch })),
    issues: plan.issues,
    branchMode: presentation.allocationMode,
    executionDescription: presentation.description,
  };
}

/** Describe an isolated branch run from its final, transformed plan. */
export function presentBranchPlan(plan: BranchPlan, options: BranchPresentationOptions = {}): BranchPresentation {
  const sharedNodes = plan.nodes.filter((node) => Boolean(node.deliveryUnitId)).length;
  const allocationMode: BranchAllocationMode = sharedNodes === 0
    ? "per-ticket"
    : sharedNodes === plan.nodes.length
      ? "shared"
      : "mixed";
  const description = options.stacked
    ? "stacked delivery branches"
    : allocationMode === "shared"
      ? "one shared branch"
      : allocationMode === "mixed"
        ? "mixed shared and per-ticket branches"
        : "one branch per ticket";

  return {
    allocationMode,
    description,
    banner: `foreman: ${options.resumed ? "resuming " : ""}${description} for ${plan.nodes.length} ticket(s)`,
    prompt: `Proceed with ${description}?`,
  };
}

export function branchNodeBehavior(node: BranchPlanNode): "shared delivery branch" | "per-ticket branch" {
  return node.deliveryUnitId ? "shared delivery branch" : "per-ticket branch";
}

export function branchNodeFooter(node: BranchPlanNode): string {
  return `Generated by Rafi ai-foreman for a ${branchNodeBehavior(node)}.`;
}
